### ISSUE TITLE
Problem to install pod

### ISSUE THREAD

**Issue by friasricardo** [ipagong/PGTabBar#3]
Hi, i can't install the pod.

The error is: [!] Unable to find a specification for `PGTabBar`

Can you help me?

**Comment by ipagong** [comment]
plz, let me know ur "podfile" 

did u add ? (top on podfile)
ㄴ "source 'https://github.com/CocoaPods/Specs.git'"

**Comment by friasricardo** [comment]
My podfile:

target 'Project' do
  use_frameworks!

  pod 'PGTabBar'
  
  target 'ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by ipagong** [comment]
i think your project is base on objc.

this code is not supported objc.
because i didn't use @objc keyword on it.

i would try to update it for objc. asap

**Comment by friasricardo** [comment]
No, my project is Swift 3

**Comment by ipagong** [comment]
if u change PGTabBar to another famous pod (like rxswift), is it ok? 
:( 
i already added "PGTabBar" at two other projects(swift3) and it didn't have any problem.

i found some similar question on stackoverflow. did you see it? 

i also wonder why the error is. ;(

**Comment by friasricardo** [comment]
I use Alamofire, SwiftJSON and both works fine, tonight i Will try use the rxswift...

**Comment by friasricardo** [comment]
I'm changed de podfile to:

pod 'PGTabBar', :git => 'https://github.com//ipagong/PGTabBar-Swift'

and now its working fine!

**Comment by ipagong** [comment]
i've found that "pod" spec git source is not correct.
i've changed it and pushed pod 0.1.7 version.
thx!
