### ISSUE TITLE
Select first TabItem on load

### ISSUE THREAD

**Issue by friasricardo** [ipagong/PGTabBar#4]
Hi,

When i load the ViewController, the last TabItem is selected (without line bottom). How can i change, to load first TabItem (with line bottom)?

Tks

**Comment by ipagong** [comment]
**for select first tabitem** :
check delegate "TabContainerDelegate" with this methods  "indexWithTabContainer"
or 
check selectAt(index) and reloadData(preferredIndex: true)

**for line bottom**:
set your custom indicator

thx

**Comment by friasricardo** [comment]
It worked!
